### PR TITLE
Feat/Refactor: Muilt minor changes

### PR DESCRIPTION
**Pull request by SukkaW**
- Feat: add cdn support for emoji

Use  jsdelivr to load emoji-cheat-sheet files.
Also use `i1.wp.com` which is known as `WordPress JetPack Free Image Optimized Service` to load twemoji, so it can have better exprience than maxcdn.

- Refactor: remove useless files related to editor.md
- Fear: add public cdn support for font-awesome, which was used at main home page

### CODE REVIEW

**Comment by CGDF-Github** [comment]
这个坑爹的jsdelivr就是之前数次搞事的那个cdn，数次ban掉sspanel里引用的文件，n次引爆机场灾难，sspanel托他所赐被迫手动revert了cdn并使用了本地文件

**Comment by CGDF-Github** [comment]
https://github.com/NimaQu/ss-panel-v3-mod_Uim/issues/181

**Comment by SukkaW** [comment]
@CGDF-Github Or you can also revert #271 as well

**Comment by CGDF-Github** [comment]
我只吐槽，既没有打算close也没有打算revert

**Comment by SukkaW** [comment]
@CGDF-Github 
As you can see, someone like @neoFelhz was abusing jsDelivr which would cause that happened.
Using jsDelivr to load open source project won't cause that.

**Pull request merged**
