### PR TITLE
Configurable copyright year & Minor vendor update

### PR DESCRIPTION
**Pull request by SukkaW**
This PR includes changes about:

- Add jsdelivr support for missing jQuery
- Migrate the qrcode.js (which was using rawgit then local) to jsDelivr
> https://www.jsdelivr.com/rawgit
- Configurable copyright year

# Breaking Change

This PR include the changes of `config.php.example` and should pay more attention.

### CODE REVIEW

**Comment by NimaQu** [comment]
@SukkaW 好耶，是苏卡卡

**Comment by NimaQu** [comment]
@SukkaW 好像少改了 app/services/config.php

**Comment by SukkaW** [comment]
@NimaQu You can add `request changes` on review and I will push a commit to fix this.

**Comment by SukkaW** [comment]
@NimaQu Fixed in https://github.com/NimaQu/ss-panel-v3-mod_Uim/pull/367/commits/0ef9ebefeed9497ef6bcf76610b32a4fa9a17257

**Pull request merged**
